server:
  port: 9100 # ????port?

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:todolist2 # h2 database ????
    driver-class-name: org.h2.Driver # ??driver
    username: sa # database ???
    password:  # database ??

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: HTML5